### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by TomMelt** [Cambridge-ICCS/FTorch#88] opened 2024-01-15 11:18 UTC
### Discussed in https://github.com/Cambridge-ICCS/FTorch/discussions/79

Possible memory leak, need to investigate further.

**Comment by jatkinson1000** [comment] 2024-03-18 09:42
Closing this as we are unable to reproduce and requests for further details have gone unanswered.
Will reopen if it reoccurs in future.

**Closed by jatkinson1000** 2024-03-18 09:42 UTC
Labels: bug
